### PR TITLE
feat: Adds trustbloc-did-method support (wasm)

### PR DESCRIPTION
**Pull request by soluchok**
This PR adds trustbloc-did-method support. did-method can be configured with the following options:
* blocDomain
* trustbloc-resolver

NOTE: `trustbloc` method can be overwritten by using `"http-resolver-url": ["trustbloc@https://uniresolver.io/1.0/identifiers"]`

Signed-off-by: Andrii Soluk <isoluchok@gmail.com>

### CODE REVIEW

**Review by aholovko — COMMENTED** [review]
@soluchok Can you plz help me to understand the scope of this PR? Isn't it about adding support for `trustbloc-did-method` to the existing resolvers? Why are we replacing the other resolvers? P.s. Excuse me if this is obvious, I am just trying to understand the direction where we are going with these changes.

**Comment by llorllale** [comment]
@soluchok like @aholovko says, we for sure need to keep the built-in framework VDRs (`did:peer`, `did:key`).

**Comment by soluchok** [comment]
> @soluchok Can you plz help me to understand the scope of this PR? Isn't it about adding support for `trustbloc-did-method` to the existing resolvers? Why are we replacing the other resolvers? P.s. Excuse me if this is obvious, I am just trying to understand the direction where we are going with these changes.

We are not replacing the other resolvers.

> @soluchok like @aholovko says, we for sure need to keep the built-in framework VDRs (`did:peer`, `did:key`).

@llorllale @aholovko `Why are we replacing the other resolvers?`  - we are not. I am not removing them. They all still here.

**Comment by aholovko** [comment]
> > @soluchok Can you plz help me to understand the scope of this PR? Isn't it about adding support for `trustbloc-did-method` to the existing resolvers? Why are we replacing the other resolvers? P.s. Excuse me if this is obvious, I am just trying to understand the direction where we are going with these changes.
> 
> > @soluchok like @aholovko says, we for sure need to keep the built-in framework VDRs (`did:peer`, `did:key`).
> 
> @llorllale @aholovko `Why are we replacing the other resolvers?` - we are not. I am not removing them. They all still here.

@soluchok code was updated, it was not a case when I added that comment ;-)

**Comment by llorllale** [comment]
@soluchok 

> @llorllale @aholovko `Why are we replacing the other resolvers?` - we are not. I am not removing them. They all still here.

I see now that the framework [is always injecting them](https://github.com/hyperledger/aries-framework-go/blob/ca5e0650014e48021c33f0c96fe23a11123967cf/pkg/framework/aries/framework.go#L353-L386) (funny and unexpected). Opened hyperledger/aries-framework-go#2268.

**Review by aholovko — APPROVED** [review]

**Review by llorllale — APPROVED** [review]

**Pull request merged**
