### PR TITLE
Not sure if I was supposed to add it to enabled tags or just delete it

### PR DESCRIPTION
**Pull request by kailynw**

### CODE REVIEW

**Comment by soluchok** [comment]
@kailynw You need only to remove it. But also you need to fix the linter.  `Checks` job on CI must pass. You can check it locally by executing `make checks`.

**Comment by llorllale** [comment]
Hi @kailynw 

Are you still working on this PR?

**Comment by kailynw** [comment]
Sorry I am not anymore.

**Comment by llorllale** [comment]
@kailynw no worries - thanks

**Pull request closed without merging**
